### ISSUE TITLE
Split Runner / Executor into separate mini-gem?

### ISSUE THREAD

**Issue by dorner** [phobos/phobos#104]
I have a totally unrelated use case where I need to use basically the same functionality that we currently have split between Cli::Runner, Executor and Listener - something that creates a bunch of threads which continually poll some resource, and need to handle signals and shut down gracefully. This functionality isn't Kafka-specific, so could we think about breaking it down into its own gem and making it a bit more generic? I actually already have the generic code more or less done, along with unit tests, so this would just be an exercise in creating the repo and the gem and setting up CI. Thoughts @klippx ?

**Comment by klippx** [comment]
Maybe you can put this mini-gem in a separate repo for now (initially on your own account), so we can see a demo of how it looks for this unrelated use case. And in addition to this, create branch of phobos (could also be on your account) to demo how it would be used in Phobos.

The fact is that this particular code is getting complex on Phobos sid, and I am positive about simplifying it. This could be done completely within Phobos though, without creating a new gem. So we'll just have to see it in action, if it looks like something people would like to use.

I think this idea needs showing to completely sell the story 😬

**Comment by dorner** [comment]
We can start with separating it out within Phobos and consider pulling those files out into a separate gem later on 👍

**Comment by klippx** [comment]
I wouldn't call this an _issue_ though, it is partly a suggestion of a new gem for a new use case, and partly a suggested approach to refactor Phobos. 

Refactoring code is good when the code becomes more digestible. I earlier said that this code was getting complex, but actually when I look at it, it could be the opposite that is true. Listener and Executor has been simplified recently and is now in quite a fine state;
- CLI::Runner is not complicated code, and not exactly in need of refactoring
- Executor is not that complex either - maybe could use some refactoring?
- Listener is a bit complex - could use some refactoring

So instead of starting by refactoring Phobos, I would say that if you feel motivated to make a gem for your unrelated use case (which borrows inspiration by Runner, Executor and Listener), please go for it. But don't constrain yourself to the boundary condition that it has to satisfy Phobos needs as well! Tailor it to your use case instead. Phobos is fine.

If you try too hard to make your idea work for both, I think you will end up harming Phobos, since moving a small surface area of the code into a gem spreads the code out, which is not a desirable state. It adds more complexity than it removes, since we have to have two code bases in mind, bundle open the other gem when debugging, and there is another gem to keep in mind for a new developer coming in to Phobos or using Phobos, makes it harder to maintain versioning (new versions of gem might break older version of Phobos), etc. 🤔

**Comment by dorner** [comment]
@klippx the changes shouldn't be too complex I don't think. Let me make a PR with it (maybe some time next week) and you can decide if it still doesn't make sense to be inside Phobos.
