### ISSUE TITLE
A way to know Phobos is running/connected to Kafka?

### ISSUE THREAD

**Issue by MiralDesai** [phobos/phobos#106]
Hey, something I'm looking into as part my application's monitoring right now. I would like to know if Phobos is running or not and whether it's got a connection to Kafka. The Kafka connection I'm less worried about since that's probably a job for ruby-kafka, not phobos.

Is it checking whether Phobos is running a possibility ? Is it something worth adding to this project? 

Maybe something like `Phobos.running?` that returns a simple boolean.

**Comment by dorner** [comment]
@MiralDesai are you talking about producers or consumers? On the producer side it doesn't really make much sense since producers are brought up and down constantly. On the consumer side, we could technically put something in there but I'm not sure it'll give you what you're looking for. The listener could be connected but not able to retrieve messages, for example.

What we've found is the number one best metric is lag (max offset - current offset) which we fire off whenever heartbeats happen. If the metric is increasing, or if we aren't getting the metric at all, we send an alert.

**Comment by klippx** [comment]
There isn't a direct API to check the number of active listeners at the moment, no.

There are ways to check this though:
- Monitor `listener.start` event https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L94
- Monitor `listener.stop` event https://github.com/phobos/phobos/blob/master/lib/phobos/listener.rb#L110
- I didn't think it was worth adding a more easier to use API at the time since it could be derived from these events.

This is exactly the approach I had for our Grafana dashboard, hooked up to Prometheus database, which is scraping Phobos consumers which are running with Phobos Prometheus Metrics
- `number_of_handlers` handler found in https://github.com/phobos/phobos_prometheus/blob/master/config/phobos_prometheus.yml.example

But I must agree with @dorner, the best way - overall - to monitor consumers is to monitor the partition lag. If -any- consumer has issues for -any- reason you will see this in the lag.

**Comment by MiralDesai** [comment]
Interesting thanks for the info guys. I was looking for a simple way to have an application health check but I will be using prometheus too so I might as well report things properly with actual data about listeners and the lag.

**Comment by amacdougall** [comment]
@dorner, I didn't want to make a new issue to ask about a related topic. Maybe you can offer some advice:

If Phobos is running in standalone mode on a dedicated node, is there a way to interrogate it from the shell?

### Context

I'm running Phobos in a Kubernetes pod with a startup command like `phobos start -b phobos_boot.rb -l my-config-file.yml`. It works just fine! But Kubernetes wants to have "probes" for containers so it knows when they're misbehaving. In particular, I want to implement a liveness probe.

The probe can be any shell script; [the documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) suggests something as simple as checking a file.

I can definitely use the Phobos `start` method to set up a heartbeat thread that continually `touch`-es a file, and then check the file's freshness in my liveness probe script. But this seems like a workaround for something that might already exist.

I see that in `Phobos::CLI::Runner#run!`, we create an executor, but that executor isn't exposed to any outside context. As an end user, I would be pleased to see a CLI command like `phobos list`, but I don't know what the implementation might be; maybe generate executor IDs and store them in a local file? The challenge would be to reliably erase the PIDs of crashed executors.

I understand that "use Prometheus and alert if something bad is happening" is the correct solution; and we're doing that! But I also want to shoehorn Phobos into the Kubernetes liveness-probe system to satisfy our overall system design.

If you're still reading this, thanks for your time! I'm open to suggestions, including the suggestion that I'm completely off track.

**Comment by dorner** [comment]
Hey @amacdougall - unfortunately we don't have something that can do this out of the box. Adding pids seems like a niche use case. As mentioned above, you can write something yourself to do this by monitoring the listener start and end events. The metadata for those events includes the group and topic IDs, so you can use those to manage your PID files if you like.

**Comment by amacdougall** [comment]
Thanks! I think my approach will be to use the startup hook to start a "heartbeat" thread that writes stats to a file on a fixed interval. If the file isn't updated in a while, or if it's updated but it reports a 0 listener count for a while, I'll consider the node a candidate for automated restart and/or alerting.

It will work just fine—just wanted to make sure I wasn't missing any related functionality.

Thanks for taking the time to respond!
