### ISSUE TITLE
Add publisher instrumentation?

### ISSUE THREAD

**Issue by MiralDesai** [phobos/phobos#108]
Just a small thing, I'm setting up the phobos-prometheus gem and I'm wondering if it's possible to capture number of messages published via a counter?

Based on this notifications provided in this gem I can already create a counter for number of messages that have been processed, can one be added for publishing messages to kafka?

**Comment by dorner** [comment]
@MiralDesai have you looked at the RubyKafka instrumentation? It provides a lot of other things you should be able to listen to and publishing messages is one of them.

**Comment by MiralDesai** [comment]
That wouldn't integrate with the phobos-prometheus gem though would it? Seems like it would be a better place to keep it all.

**Comment by dorner** [comment]
Correct - in that case it might be a request on that gem instead of this one to start sending the Kafka instrumentation. There is way more data available on the Kafka gem than the Phobos one.

**Comment by klippx** [comment]
In order to achieve this, we would need a PR that adds phobos instrumentation around producing a message. This is because phobos-prometheus uses `Phobos::Instrumentation.subscribe` which limits the namespace of active support events to `phobos` only ([reference](https://github.com/phobos/phobos/blob/master/lib/phobos/instrumentation.rb#L7)).

If that is done, then it is a trivial config change in phobos-prometheus to achieve this, e.g:

```
counters:
  - instrumentation: producer.produce_message
```

I think this is the best option since this is a plugin/integration to Phobos. I wouldn't purse the idea of using `ActiveSupport::Notifications.instrument` directly in order to get ruby-kafka metrics even if more data is available there.

Another, more ambitious option is to evolve the phobos-prometheus config to have a `phobos` section and a `ruby-kafka` section. And then have separate logic subscribing to ruby kafka active support (not using `Phobos::Instrumentation.subscribe` and following ruby-kafka naming metrics naming convention).

e.g.

```
metrics_prefix: phobos_app

phobos:
  counters:
    - instrumentation: listener.process_message
    - instrumentation: listener.process_batch

ruby-kafka:
  counters:
    - instrumentation: produce_message.producer
```

But tbh I think it is a bit outside the scope of a gem called "phobos-prometheus" so I would prefer to just add instrumentation to phobos like I explained in the first option.
